name: Semantic release
on:
  push:
    branches:
      - main

jobs:
  # Run semantic release on main branch
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: semantic-release
          path: |
            phylodm/__init__.py
            CHANGELOG.md
          retention-days: 1
